version: '3.9'

volumes:
  fooocus-data:

services:
  app:
    build: .
    image: kalazus/fooocus
    ports:
     - 3001:3001
    environment:
      - CMDARGS=--always-gpu   # Arguments for entry_with_update.py.
      - DATADIR=/content/data   # Directory which stores models and the outputs dir
    volumes:
      - fooocus-data:/content/data
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
